### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by Malin-Malin** [Malin-Malin/CommunityScienceMuseum#2]
- [x] High-definition prototype for desktop- write for mobile (2 points)
- [ ] UX/UI: Responsiveness and accessibility (2 point)
- [ ]  HTML is bug-free and semantic (2 points)
- [ ]  CSS follows DRY principles (2 points)
- [ ]  Website is responsive (4 points)
- [x]  Each page has unique titles and descriptions (1 point)
- [x]  Each page has a unique H1 (1 point)
- [x]  Images are below 200kb (1 point)
- [ ]  Colors are WCAG compliant (1 point)
- [x]  Images have alt text (1 point)
- [ ]  Project is well-organized and files are formatted (1 point)
- [x]  Report includes lessons learned and challenges (1 point)
- [ ]  Project successfully planned and completed (1 point)
